AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/support/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'node_modules/**/*'

Layout:
  Enabled: true
Lint:
  Enabled: true
Metrics:
  Enabled: true
Performance:
  Enabled: true
Bundler:
  Enabled: true
Gemspec:
  Enabled: true
Security:
  Enabled: true
Rails:
  Enabled: true
Naming:
  Enabled: true
Style:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Style/AsciiComments:
  Enabled: false # Use only ascii symbols in comments.
Style/Documentation:
  Enabled: false # "Missing top-level class documentation comment"
Style/FrozenStringLiteralComment:
  Enabled: false # "Missing magic comment # frozen_string_literal: true"
Rails/FilePath:
  Enabled: false
